### ISSUE TITLE
Memory leak in 1.8.1

### ISSUE THREAD

**Issue by mckernanin** [mgcrea/prisma-queue#2]
On upgrading my application from 1.7 to 1.8.1, my container memory usage went from ~200mb average to constantly running out of memory at my memory limit of 750mb. pgbouncer was also over 50%+ CPU usage. Upon downgrading to 1.7.0 (and leaving all other packages the same) the issue went away (memory usage back in check, postgres cpu averaging 1% across 2 cores.

RAM Usage:
![image](https://github.com/mgcrea/prisma-queue/assets/6300047/7337be5c-7281-4334-9211-4f7a84593126)

CPU Usage:
![image](https://github.com/mgcrea/prisma-queue/assets/6300047/d1edec77-975e-4337-b46d-e3ada17bb7c2)

**Comment by mckernanin** [comment]
I'm using a concurrency of 2, the container in question is only running the queue processing. I'll do some testing when I have time and try to narrow down the issue in my local environment.

**Comment by mgcrea** [comment]
@mckernanin I have reverted the change and released a new `1.9.0` release without it, looking at the code again, it is pretty obvious that it will lead to memory leaks as you end up with X poll() function that have never ending while loops.

Thanks again!
