### ISSUE TITLE
Supporting external prisma client / in a monorepo

### ISSUE THREAD

**Issue by noxify** [mgcrea/prisma-queue#6]
Hi,

I love this package since it's easy to use and it just work!

We're currently using it in a monorepo, where the prisma client is located in a dedicated package.

To make prisma-queue work in this approach, we have to copy the repo code (into a package) and update all imports to reference to the db package.

What do you think about allowing to pass a prisma instance while initiating a queue?

If it's out of scope, that's ok - our current workaround works and we just have to check your repo if there are new updates to ensure we're up to date.

If you need a demo repo how it looks like, please let me know.

Thanks again for all the work ❤️

**Comment by mgcrea** [comment]
Thanks for the kind words,

I think you should already be able to pass a `prisma` (PrismaClient) option and it should just work, see https://github.com/mgcrea/prisma-queue/blob/master/src/PrismaQueue.ts#L19

Not using it so it might be broken somehow, let me know if it does not work and will fix it asap :).

Have a nice day.

**Comment by noxify** [comment]
Will give it a try tomorrow - thanks for the quick response

**Comment by noxify** [comment]
> I think you should already be able to pass a prisma (PrismaClient) option and it should just work, see:

thanks for the hint - it seems to work in the dev mode ( haven't tried it with a prod build, but should work ).

I assumed that 

```
import { Prisma, PrismaClient } from "@prisma/client";
```

will produce an error ( since there is no @prisma/client ) inside the queue package and the queue app.
Fortunately, I was wrong.

Thanks again for the quick help <3
